version: '3.3'
services:
  db:
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    image: kubanez/backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: kubanez/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/etc/nginx/html/static/
      - media_value:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
  static_value:
  media_value:
