# Generated by Django 3.2.16 on 2023-04-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipes_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipes',
            name='unique recipe',
        ),
    ]
