# Generated by Django 3.2.16 on 2023-03-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='shopping_cart',
            field=models.ManyToManyField(default=None, to='api.Recipes'),
        ),
    ]
