# Generated by Django 3.2.16 on 2023-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
