# Generated by Django 3.2.16 on 2023-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230326_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='amount',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
