# Generated by Django 3.2.16 on 2023-03-31 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_recipes_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping', to=settings.AUTH_USER_MODEL),
        ),
    ]
