# Generated by Django 3.2.16 on 2023-03-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ingredients_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='is_favored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False),
        ),
    ]
