# Generated by Django 3.2.16 on 2023-03-27 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='is_favored',
        ),
        migrations.AddField(
            model_name='recipes',
            name='is_favored',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='is_in_shopping_cart',
        ),
        migrations.AddField(
            model_name='recipes',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
